import cv2
import numpy as np
img=cv2.imread('baboon.jpg')
cv2.namedWindow('Original image')
cv2.imshow('Original',img)
cv2.imwrite('ori.jpg',img)
print("RGB value: ",img[20,25])
B,G,R=cv2.split(img)
cv2.imshow("Blue",B)
cv2.imshow("Green", G)
cv2.imshow("Red",R)
cv2.imwrite("Blue.jpg",B)
cv2.imwrite("Green.jpg",G)
cv2.imwrite("Red.jpg",R)

YCrCb=cv2.cvtColor(img,cv2.COLOR_BGR2YCR_CB)
print("YCrCb value: ",YCrCb[20,25])
y,cb,cr=cv2.split(YCrCb)
cv2.imshow("Y",y)
cv2.imshow("Cb", cb)
cv2.imshow("Cr",cr)
cv2.imwrite("Y.jpg",y)
cv2.imwrite("Cb.jpg",cb)
cv2.imwrite("Cr.jpg",cr)

hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
print("HSV value: ",hsv[20,25])
hue,saturation,value=cv2.split(hsv)
cv2.imshow("Hue",hue)
cv2.imshow("Saturation", saturation)
cv2.imshow("Value",value)
cv2.imwrite("Hue.jpg",hue)
cv2.imwrite("Saturation.jpg",saturation)
cv2.imwrite("Value.jpg",value)
cv2.waitKey(0)